/**
 * Service Injection Tokens for NestJS ClientsModule
 */
export const SERVICES = {
  USER_SERVICE: 'USER_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',
  ORDER_SERVICE: 'ORDER_SERVICE',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  RABBITMQ_SERVICE: 'RABBITMQ_SERVICE',
} as const;

export type ServiceName = (typeof SERVICES)[keyof typeof SERVICES];
